rules = [
#  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal
]

DisableSyntax {
  keywords = [
#     var,
#    null,
    return
  ]
#  noAsInstanceOf = true
  noIsInstanceOf = true
  noWhile = true
  noXml = true
}

OrganizeImports {
  groupedImports = Merge
  groupExplicitlyImportedImplicits = true
  removeUnused = true
  expandRelative = true
}